#!/usr/bin/env node
"use strict";

const fs = require("fs");
const path = require("path");
const vm = require("vm");

function parseArgs(argv) {
  const args = {
    out: "downloads/diter_standalone.js",
    deps: "downloads/diter_dependencies.json",
    module: "kbo/",
    chunks: null,
  };
  for (let i = 0; i < argv.length; i += 1) {
    const arg = argv[i];
    if (arg === "--out") {
      args.out = argv[++i];
    } else if (arg === "--deps") {
      args.deps = argv[++i];
    } else if (arg === "--module") {
      args.module = argv[++i];
    } else if (arg === "--chunks") {
      args.chunks = argv[++i];
    }
  }
  return args;
}

function loadChunks(chunkPaths) {
  const registry = {};
  const chunks = [];
  chunks.push = function push(chunk) {
    const modules = chunk && chunk[1];
    if (modules && typeof modules === "object") {
      Object.assign(registry, modules);
    }
  };

  global.self = global;
  global.window = global;
  global.webpackChunksketchfab = chunks;

  for (const chunkPath of chunkPaths) {
    if (!fs.existsSync(chunkPath)) {
      throw new Error(`Chunk not found: ${chunkPath}`);
    }
    const code = fs.readFileSync(chunkPath, "utf8");
    vm.runInThisContext(code, { filename: chunkPath });
  }

  return registry;
}

function escapeRegExp(value) {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

function getRequireIdentifier(src) {
  const arrowMatch = src.match(/^\s*\(?\s*([^)]*?)\s*\)?\s*=>/);
  if (arrowMatch) {
    const params = arrowMatch[1].split(",").map((value) => value.trim()).filter(Boolean);
    return params[2] || null;
  }
  const functionMatch = src.match(/function\s*[^(]*\(([^)]*)\)/);
  if (functionMatch) {
    const params = functionMatch[1].split(",").map((value) => value.trim()).filter(Boolean);
    return params[2] || null;
  }
  return null;
}

function extractDependencies(factory) {
  const deps = new Set();
  const src = factory.toString();
  const requireIdent = getRequireIdentifier(src);
  if (!requireIdent) {
    return [];
  }
  const ident = escapeRegExp(requireIdent);
  const callRe = new RegExp(`\\b${ident}\\(([^)]*)\\)`, "g");
  let match = null;
  while ((match = callRe.exec(src)) !== null) {
    const args = match[1];
    const stringMatch = args.match(/["']([^"']+)["']/);
    if (stringMatch) {
      deps.add(stringMatch[1]);
      continue;
    }
    const numberMatch = args.match(/\\b([0-9]+)\\b/);
    if (numberMatch) {
      deps.add(String(numberMatch[1]));
    }
  }
  return Array.from(deps).sort();
}

function buildGraph(entryId, registry) {
  const graph = new Map();
  const externals = new Set();
  const stack = [entryId];

  while (stack.length) {
    const id = stack.pop();
    if (graph.has(id)) {
      continue;
    }
    const factory = registry[id];
    if (!factory) {
      externals.add(id);
      continue;
    }
    const deps = extractDependencies(factory);
    graph.set(id, deps);
    for (const dep of deps) {
      if (registry[dep]) {
        stack.push(dep);
      } else {
        externals.add(dep);
      }
    }
  }

  return { graph, externals };
}

function topoSort(entryId, graph) {
  const ordered = [];
  const temporary = new Set();
  const permanent = new Set();

  function visit(id) {
    if (permanent.has(id)) {
      return;
    }
    if (temporary.has(id)) {
      return;
    }
    temporary.add(id);
    const deps = graph.get(id) || [];
    for (const dep of deps) {
      if (graph.has(dep)) {
        visit(dep);
      }
    }
    temporary.delete(id);
    permanent.add(id);
    ordered.push(id);
  }

  visit(entryId);
  return ordered;
}

function writeStandalone(entryId, registry, graph, orderedIds, outPath) {
  const lines = [];
  lines.push('"use strict";');
  lines.push("");
  lines.push("// Auto-generated by scripts/extract_diter.js");
  lines.push("const __registry = {};");
  for (const id of orderedIds) {
    const factory = registry[id];
    if (!factory) {
      continue;
    }
    lines.push(`__registry[${JSON.stringify(id)}] = ${factory.toString()};`);
  }

  lines.push("");
  lines.push("const __cache = {};");
  lines.push("function __webpack_require__(id) {");
  lines.push("  if (__cache[id]) {");
  lines.push("    return __cache[id].exports;");
  lines.push("  }");
  lines.push("  const factory = __registry[id];");
  lines.push("  if (!factory) {");
  lines.push('    throw new Error(`Module not found: ${id}`);');
  lines.push("  }");
  lines.push("  const module = { exports: {} };");
  lines.push("  __cache[id] = module;");
  lines.push("  factory.call(module.exports, module, module.exports, __webpack_require__);");
  lines.push("  return module.exports;");
  lines.push("}");
  lines.push("");
  lines.push("__webpack_require__.d = (exports, definition) => {");
  lines.push("  for (const key in definition) {");
  lines.push("    if (Object.prototype.hasOwnProperty.call(definition, key) && !Object.prototype.hasOwnProperty.call(exports, key)) {");
  lines.push("      Object.defineProperty(exports, key, { enumerable: true, get: definition[key] });");
  lines.push("    }");
  lines.push("  }");
  lines.push("};");
  lines.push("");
  lines.push("__webpack_require__.n = (module) => {");
  lines.push("  const getter = module && module.__esModule ? () => module.default : () => module;");
  lines.push("  __webpack_require__.d(getter, { a: getter });");
  lines.push("  return getter;");
  lines.push("};");
  lines.push("");
  lines.push("__webpack_require__.o = (obj, prop) => Object.prototype.hasOwnProperty.call(obj, prop);");
  lines.push("");
  lines.push("__webpack_require__.r = (exports) => {");
  lines.push('  if (typeof Symbol !== "undefined" && Symbol.toStringTag) {');
  lines.push('    Object.defineProperty(exports, Symbol.toStringTag, { value: "Module" });');
  lines.push("  }");
  lines.push('  Object.defineProperty(exports, "__esModule", { value: true });');
  lines.push("};");
  lines.push("");
  lines.push(`module.exports = __webpack_require__(${JSON.stringify(entryId)});`);

  fs.mkdirSync(path.dirname(outPath), { recursive: true });
  fs.writeFileSync(outPath, lines.join("\n"));
}

function writeDeps(entryId, graph, externals, outPath) {
  const payload = {
    entry: entryId,
    modules: Array.from(graph.keys()).sort(),
    edges: Object.fromEntries(Array.from(graph.entries())),
    externals: Array.from(externals).sort(),
  };
  fs.mkdirSync(path.dirname(outPath), { recursive: true });
  fs.writeFileSync(outPath, JSON.stringify(payload, null, 2));
}

function main() {
  const args = parseArgs(process.argv.slice(2));
  const chunkPaths = args.chunks
    ? args.chunks.split(",").map((value) => value.trim()).filter(Boolean)
    : [
        "js_downloads/remote/ec580af0b531503f94c740ca2873c32e-v2.js",
        "js_downloads/remote/5bcaa88525fab96faffe19e1ce66716c-v2.js",
        "js_downloads/remote/7aa463e7a4f2c770ab2436d6def75af2-v2.js",
        "js_downloads/remote/a25387388d9ea5501c87029166d396ac-v2.js",
      ];

  const registry = loadChunks(chunkPaths);
  if (!registry[args.module]) {
    throw new Error(`Module not found in registry: ${args.module}`);
  }

  const { graph, externals } = buildGraph(args.module, registry);
  const orderedIds = topoSort(args.module, graph);

  writeStandalone(args.module, registry, graph, orderedIds, path.resolve(args.out));
  if (args.deps) {
    writeDeps(args.module, graph, externals, path.resolve(args.deps));
  }

  console.log(`Wrote standalone module to ${args.out}`);
  if (args.deps) {
    console.log(`Wrote dependency graph to ${args.deps}`);
  }
  if (externals.size) {
    console.log(`External references: ${Array.from(externals).join(", ")}`);
  }
}

try {
  main();
} catch (err) {
  console.error(err.message || err);
  process.exit(1);
}
