/* Automatically generated by wasm2c */
#ifndef DITER_WASM_BLOB_WASM2C_H_GENERATED_
#define DITER_WASM_BLOB_WASM2C_H_GENERATED_

#include "diter_rt.h"

#include <stdint.h>

#ifndef WASM_RT_CORE_TYPES_DEFINED
#define WASM_RT_CORE_TYPES_DEFINED
typedef uint8_t u8;
typedef int8_t s8;
typedef uint16_t u16;
typedef int16_t s16;
typedef uint32_t u32;
typedef int32_t s32;
typedef uint64_t u64;
typedef int64_t s64;
typedef float f32;
typedef double f64;
#endif

#ifdef __cplusplus
extern "C" {
#endif

struct w2c_env;
extern wasm_rt_memory_t* w2c_env_memory(struct w2c_env*);

typedef struct w2c_diter__wasm__blob {
  struct w2c_env* w2c_env_instance;
  /* import: 'env' 'memory' */
  wasm_rt_memory_t *w2c_env_memory;
  u32 w2c_g0;
  wasm_rt_funcref_table_t w2c_T0;
} w2c_diter__wasm__blob;

void wasm2c_diter__wasm__blob_instantiate(w2c_diter__wasm__blob*, struct w2c_env*);
void wasm2c_diter__wasm__blob_free(w2c_diter__wasm__blob*);
wasm_rt_func_type_t wasm2c_diter__wasm__blob_get_func_type(uint32_t param_count, uint32_t result_count, ...);

/* import: 'env' 'abort' */
void w2c_env_abort(struct w2c_env*);

/* import: 'env' 'sbrk' */
u32 w2c_env_sbrk(struct w2c_env*, u32);

extern const u64 wasm2c_diter__wasm__blob_min_env_memory;
extern const u64 wasm2c_diter__wasm__blob_max_env_memory;
extern const u8 wasm2c_diter__wasm__blob_is64_env_memory;
extern const u32 wasm2c_diter__wasm__blob_pagesize_env_memory;

/* export: '__wasm_call_ctors' */
void w2c_diter__wasm__blob_0x5F_wasm_call_ctors(w2c_diter__wasm__blob*);

/* export: 'heSBnb29kYnllCk5ldmVyIGdvbm5hIHRl' */
u32 w2c_diter__wasm__blob_heSBnb29kYnllCk5ldmVyIGdvbm5hIHRl(w2c_diter__wasm__blob*, u32);

/* export: 'mV2ZXIgZ29ubmEgbGV0IHlvdSBkb3duCk5l' */
void w2c_diter__wasm__blob_mV2ZXIgZ29ubmEgbGV0IHlvdSBkb3duCk5l(w2c_diter__wasm__blob*);

/* export: 'Umlja1JvbGxlZDRV' */
u32 w2c_diter__wasm__blob_Umlja1JvbGxlZDRV(w2c_diter__wasm__blob*, u32, u32);

/* export: 'dmVyIGdvbm5hIHJ1biBhcm91bmQgYW5kI' */
u32 w2c_diter__wasm__blob_dmVyIGdvbm5hIHJ1biBhcm91bmQgYW5kI(w2c_diter__wasm__blob*, u32);

/* export: 'GRlc2VydCB5b3UKTmV2ZXIgZ29ubmEgbW' */
u32 w2c_diter__wasm__blob_GRlc2VydCB5b3UKTmV2ZXIgZ29ubmEgbW(w2c_diter__wasm__blob*);

/* export: 'FrZSB5b3UgY3J5Ck5ldmVyIGdvbm5hIHN' */
void w2c_diter__wasm__blob_FrZSB5b3UgY3J5Ck5ldmVyIGdvbm5hIHN(w2c_diter__wasm__blob*);

/* export: 'bGwgYSBsaWUgYW5kIGh1cnQgeW91Cg' */
u32 w2c_diter__wasm__blob_bGwgYSBsaWUgYW5kIGh1cnQgeW91Cg(w2c_diter__wasm__blob*);

/* export: 'TmV2ZXIgZ29ubmEgZ2l2ZSB5b3UgdXAKT' */
u32 w2c_diter__wasm__blob_TmV2ZXIgZ29ubmEgZ2l2ZSB5b3UgdXAKT(w2c_diter__wasm__blob*);

#ifdef __cplusplus
}
#endif

#endif  /* DITER_WASM_BLOB_WASM2C_H_GENERATED_ */
